### ISSUE TITLE
Suggestion: a11y-dialog

### ISSUE THREAD

**Issue by KittyGiraudel** [dspace-projects/additions#3]
Good morning,

I have noticed [react-a11y-dialog](https://github.com/HugoGiraudel/react-a11y-dialog) is already in the list, however the underlying actual accessible component, [a11y-dialog](https://github.com/edenspiekermann/a11y-dialog), is not. It might be worth adding. :)

**Comment by dspace-projects** [comment]
Already in: https://ds.gpii.net/content/react-a11y-dialog

**Comment by KittyGiraudel** [comment]
No, they are different projects. One is a react component, one is a vanilla JS library.
