### ISSUE TITLE
Suggestion: inclusive-menu-button

### ISSUE THREAD

**Issue by KittyGiraudel** [dspace-projects/additions#6]
Good morning,

[inclusive-menu-button](https://github.com/Heydon/inclusive-menu-button) is a splendid library from @heydon to create accessible menu button components (sort of dropdown style).

Definitely worth adding to the list. :)

**Comment by dspace-projects** [comment]
Thx. Queued for moderation!

**Comment by dspace-projects** [comment]
Done https://ds.gpii.net/content/inclusive-menu-button, but my feeling is this should be specifically listed for blind and physical disabilities (currently other/unspecified).
