### ISSUE TITLE
Suggestion: react-menu-button

### ISSUE THREAD

**Issue by KittyGiraudel** [dspace-projects/additions#7]
Good morning,

[react-menu-button](https://github.com/HugoGiraudel/react-menu-button) is a React wrapper around [inclusive-menu-button](https://github.com/Heydon/inclusive-menu-button) from @heydon (see #6).

Could be worth adding. :)

**Comment by dspace-projects** [comment]
Thx! Queued for moderation on ds.gpii.net

**Comment by dspace-projects** [comment]
https://ds.gpii.net/content/react-menu-button

interestingly differently tagged than the inclusive-menu-button...

Particularly that reduced number of inputs is selected as a solution, but physical disabilities are not particularly addressed.
